version: '3.8'
services:
  velocity-mongo:
    image: mongo:4.0.4
    volumes:
      - ./mongo:/data
    ports:
      - 27018:27017

  credentialagent:
    image: ghcr.io/velocitynetworkfoundation/packages/credentialagent:testnet
    env_file:
      - .env
    ports:
      - 8080:3000
    restart: on-failure
    depends_on:
      - velocity-mongo

